### ISSUE TITLE
Could you explain header of result?

### ISSUE THREAD

**Issue by PavitaKae** [zstephens/exogene#5]
Could you explain each column in integrations.tsv? I confuse about meaning of header row.

**Comment by zstephens** [comment]
Greetings! The first 5 columns should be self-explanatory, here's a summary of the rest:

`ANNOTATION` - intersections with problematic regions, e.g. centromeres, or regions known to be similar to viral sequence
`SOFTCLIP_POS` - the position of the integration that is supported by the largest number of softclipped short reads
`#SOFTCLIP` - the total number of softclipped short reads
`SOFTCLIP_MAPQ0` - the percentage of softclipped short reads that were aligned with mapping quality 0 (it's good if this is low)
`DISCORDANT_POS` - our best estimate for the position of the integration based on discordant short read pairs
`#DISCORDANT` - the total number of discordant read pairs
`LONGREAD_POS` - the position of the integration according to long reads (if they were provided)
`#LONGREAD` - the total number of long reads
`#HIFI/CLR` - the number of hifi reads / the number of clr reads. I admit that this is a bit out of date as very few people are using CLR reads nowadays.
`#MAPQ0_HIFI/CLR` - the percentage of long reads that were aligned with mapping quality 0, also split into hifi / clr

Hope this helps!
